version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "80:80"
    depends_on: 
      - postgres

  app:
    container_name: nest_app_container
    image: node:lts-alpine
    user: "node"
    working_dir: /app
    volumes: 
      - ./:/app
    ports:
      - "3000:3000"
    command: "npm run start"
    depends_on: 
      - postgres

volumes:
    postgres:
    pgadmin: